# Generated by Django 5.2.7 on 2025-11-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_alter_receta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
